apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: ecommerce-dev
  labels:
    app: product-service
    environment: dev
data:
  PORT: "3001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  DB_USER: "postgres"