apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-dev
  labels:
    app: product-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-service
        environment: dev
    spec:
      containers:
        - name: product-service
          image: rileymo97/product-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: product-service-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"