apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-dev
  labels:
    app: product-service
    environment: dev
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP