apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce-dev
  labels:
    app: frontend
    environment: dev
data:
  REACT_APP_PRODUCT_SERVICE_URL: "http://localhost:3001"
  REACT_APP_ORDER_SERVICE_URL: "http://localhost:3002"