apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ecommerce-dev
  labels:
    app: frontend
    environment: dev
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort